### ISSUE TITLE
Details on speedup

### ISSUE THREAD

**Issue by vidit98** [humansensinglab/taming-3dgs#1]
Thanks for your great work! May I know what are the changes that result in speed up other than sparse adam. In the readme I see two results ours and ours with sparse adam. What are the changes in "ours" that make it fast compared to 3DGS?

**Comment by rahul-goel** [comment]
Hi, the speed ups to Vanilla 3DGS are due to a better backward pass, fully fused SSIM and resolving other bottlenecks. 

Currently, in the table, "Ours" is using the Adam optimizer and hence will give the same results as 3DGS. "Ours + Sparse Adam" uses the SparseAdam optimizer which will give slightly degraded results at a better speed.

We also propose a different densification and a different optimizer in our paper (https://humansensinglab.github.io/taming-3dgs/). The code for that will be released in late November as mentioned in the updated README.
